### ISSUE TITLE
Nexpose Severity Not Importing

### ISSUE THREAD

**Issue by cgalligan** [rackerlabs/django-DefectDojo#87]
When I import a Nexpose xml scan, the severity levels (critical, severe, moderate) are not importing correctly.

**Comment by devGregA** [comment]
Hi @cgalligan would it be possible to get a sample scan? I don't have a nexpose xml file to debug with. @grendel513 are you still at RAX / be able to look into it internally?

**Comment by grendel513** [comment]
@devGregA @cgalligan - I will be at the Castle tomorrow and can touch base.

**Comment by grendel513** [comment]
@cgalligan @devGregA - worked with Ali and we determined that there is no need for code changes, the severity levels are being mapped correctly.  As it turns out he was not generating the appropriate report format from Nexpose.  The format has to be Nexpose XML 2.0, which is a canned report format.  Closing.
